artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_data : allandclive/chicken-disease-1
  local_data_file: artifacts/data_ingestion/
  unzip_dir: artifacts/data_ingestion/
  kaggle_path : C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\.kaggle


prepare_base_model: 
  root_dir : artifacts/prepare_base_model
  base_model_path : artifacts/prepare_base_model
  updated_base_model_path : artifacts/prepare_base_model/base_model_updated.h5
  

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir : /artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath : /artifacts/prepare_callbacks/checkpoint_dir/model.h5
