artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_data : allandclive/chicken-disease-1
  local_data_file: artifacts/data_ingestion/
  unzip_dir: artifacts/data_ingestion/
  kaggle_path : C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\.kaggle

data_structure:
  unprocessed_data : artifacts/data_ingestion
  processed_data : artifacts/processed_data
  train_folder_sal : artifacts/processed_data/train/Salmonella
  test_folder_sal : artifacts/processed_data/test/Salmonella
  train_folder_cocc : artifacts/processed_data/train/Coccidiosis
  test_folder_cocc : artifacts/processed_data/test/Coccidiosis




prepare_base_model: 
  root_dir : artifacts/prepare_base_model
  base_model_path : artifacts/prepare_base_model
  updated_base_model_path : artifacts/prepare_base_model/base_model_updated.h5
  

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir : /artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath : /artifacts/prepare_callbacks/checkpoint_dir/model.h5
